[package]
name = "terminarr"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = { version = "0.3" }
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = {version = "1.0.130" , features = ["derive"]}
serde_json = "1.0"
confy = "0.3.1"
